# Acknowledgements {-}
First and foremost, I would like to thank my advisor, Vasiliy, for his patience and continuous support as I changed the scope of my thesis over and over, well into February. Also go us for getting the biggest sample size in a thesis, maybe ever?

Additionally, thank you to Greg for helping me figure out how to use magic i.e. use PCA, which I think most people will probably end up thinking is magic but whatever. It's just an undergraduate thesis. Sorry that I stopped coming to class but still came to your office hour for thesis help haha.

I would also like to thank my roommate and best friend Isaac for revealing to me the true, nefarious purpose of homosexuality, which I am now sworn to take to the grave without telling another soul. Also thanks for cooking me dinner almost every day for that two week period where I didn't go to class and just worked on my thesis and talked about girls. You are the truly the best fag a dyke could ask for. 

Also, thank you to my pal of pals and thesis desk partner Lou, who, regardless of the pronouns I was in to, was always by side and down to banter in a variety of accents and codes for four straight years! Four years! Alright! Cheerio! 

Thank you to Riley who accompanied me in IRL life, and then via FaceTime as the pandemic fell over Oregon, in my descent into madness as I began realizing that, while the semester was ending, the completion thesis was not. You're quite funny *very* pretty, *even* for a tranny. See you tomorrow. 

Thank you to Jay who transitioned from cycling buddy to R Markdown buddy as you graduated and I started thesis. Hopefully we can detransition soon. 

Thank you to all of my dear gender-diverse feminists: Io, Schuster, Nell, and Zoe. While I don't think we actually settled on a definition of "gender diverse," I'm glad that we were able to exercise that term enough for me to feel confident using it in my thesis title and never define it in the text. 

Thank you to Paulina, whose overflowing passion for fancy liquids and weird modern classical music knows no geographical bounds i.e. not Oregon i.e. Chicago. Let's do that again sometime. 

Thank you to Vivek, whose camradery in high quality music and appreciation for Paul was a continuous sorce of joy over the years. It's a shame you chose the worse major—neuroscience—so we'll never truly be on equal footing, but I see you and I appreciate you. Also thanks for your short-lived TA role with Beef Tip helping us teach Ophelia to press the lever on her *other* right. 

Thank you to Saxton, who *also* sat with me on the lawn as the world switched up it vibes. Because I got an extension on my thesis, I have the privlege of ripping your acknowledgement text for mine. 

Thank you to Saga who entertained bit after bit in the PARC when they really had no choice because they were at work. Also thank you for finally revealing the author's rhetorical purpose in your thesis. While I don't personally grasp what "g\*y s\*x" means, I trust you and the personal significance it holds for you. 

Thank you to my dear Reed College dolls: Mia, Beatrice, and Winn. How very feminist of us to queer higher-ed and our small liberal arts college in the Portland Northwest by transitioning while studying. Stunning. 

Thank you to the REED COLLEGE LOW BRASS SECTION! We really brought that Reed College sound for FOUR YEARS in a row! Don't you all remember four years ago? With Yuan? Anyone? Thank you to all of the Low Brass underclassmen, Henry, Jon, and Gloria, who bought Ryen and I pizza seemingly every night this semester until the 2019–20 coronavirus pandemic put a halt to all of that. 

Thank you to Kristin, whose continuous encouragement, support, and interest in my work in and out of the mLab pushed me to new levels. 

Thank you to Dr. Kelly "Preisdent of Solid Air" Chacón PhD Esq., whose, frankly, *ridiculous* tollerance of my bits blossomed into a wonderful friendship. In your own words, I now know neither physics nor chemistry. But, I have a friend. Additionally, thank you to Luke and Pax for your impressive and continuous commitment to the bit. Also hi Alex!

Thank you also to everyone who attended the Tuesday Transgender injection Zoom meeting, including Benjamin, Shaan, Iris, Maddox, Beq, Winn, and August. How cool of us to be transgender in the time of COVID.

Thank you to the many people who sent me kind words of encouragement when I was frustrated that the pronouns just weren't adding up. There are too many of you to thank, but I appreciate all of you and you help lift this thesis to what it is today. 

Thank you KDFC, for continuously entertaining me from 8:30am-ish to 10-10:30-ish every day for the past four years. I have but one small suggestion: please replace the Classical Commuter Quiz and the Musical Blind Date with additional segments of Mozart in the Morning, they are not necessary and Mozart is better. Thanks.

And most importantly, to Tuesday, as in the day of the week. You were always there for me. Truly you make the natiform indent in meaning that falls between Monday and Wednesday. Thanks, Tuesday.

# Dedication {-}
  
I would like to dedicate this thesis to my mother, whose continuous support in every part of my life has made this thesis and so much more possible. I love you, mom. 