# Literature Review 

This section begins by outlining the principals that guided the research and development of this study. This is followed by a review of the literature on gender identity, trans identities, and the limited literature on gendered pronouns.

## Research Principals

The author is a Chinese-American woman who is transgender and a butch lesbian. In a previous period of her life, she identified as non-binary. Much of the research and design of this study has been guided by her experiences with gender. In this literature review, there were several guiding principals that she used to evaluate and include pieces of literature. 

Firstly, the author believes that gender is infinitely multifaceted, and, importantly for the purposes of this study, does not fall into a binary or trinary system. While there is certainly value in labels and identities, she does not believe that gender can be described with a single axis. That is to say that, while there is value in identities such as masculine and feminine and identities that fall in between or combine the two, it is vital to not confine oneself to a single system. 

Thus, research that treated gender as a binary was excluded. This includes measures such as the Utrecht Gender Dysphoria Scale [@schneiderMeasuringGenderDysphoria2016], which, while important as a start into giving clinicians tools to care for trans individuals, still treats gender as fundamentally linked to genitals and sex characteristics that can be neatly divided into a binary. This scale fundamentally fails non-binary patients and patients who may feel euphoric about certain aspects of their body and gender, but not others. 

This is, of course, an imperfect effort. Limitations in language used to discuss gender may still presuppose a gender binary. For example, the term "non-binary" can be used to describe anyone who's gender does not fit into the categories of "man" and "woman" [@richardsNonbinaryGenderqueerGenders2016]. However, the term exists in opposition to "binary," thereby presupposing the existence of "binary" gender categories. The term "non-binary" is critical to this study. However, the author has made a deliberate effort to *not* treat "binary" as a coherent class of gendered experience. 

Secondly, the author believes that gender identity is entirely separate from sex assigned at birth. While it's true that cisgender people may have a hard time believing this, as their experience of gender has been entirely or mostly congruent with the sex they were assigned at birth [@hollebAZGenderSexuality2019], for trans and non-binary people, this narrative can be casually harmful at best, to deeply violent at worst. Sex and gender assigned at birth was intentionally excluded from this study, as the author believes that present gender identity should be the sole focus in studies of gender identity and gendered social experiences. 

Finally, the author believes that there are no fundamental differences between cisgender men and women and transgender men and women. That is, there is nothing "essential" that cisgender people possess and know about their gender that transgender people fundamentally cannot also know or experience. Even arguments that center reproductive organs or certain bodily functions break down when sex is framed as construct and intersex people are recognized [@ezieDeconstructingBodyTransgender2010]. Therefore, research that centered sex assigned at birth or presupposed fundamental differences between trans and cis gender identities was excluded. 

## Gender Identity

For some, gender is simply a stand-in term for sex [@auerbachSWSPRESIDENTGender1999]. This means that many people simply understand sex and gender to be the same thing—one is born a male and grows up to be a man or is born female and grows up to be a woman. However, this does not hold up once one acknowledges the diverse array of gender expressions and identities that exist. 

Gender identity is better understood as one's internal sense of gender and the gendered social roles that they choose [@kuperGenderIdentityDevelopment2018]. Generally, @kuperGenderIdentityDevelopment2018 frame gender identity adoption as an affirming process, in which one adopts the roles that most affirms their gender identity. Gender expression is the outward appearance one chooses in order to express their internal gender identity. 

It should be noted that the roles that one relates to when forming one's gender identity are not limited to "man" and "woman," nor are they fixed over time. @diamondTransgenderExperienceIdentity2011 argues that gender identity is formed over time and is a constant process of changing one's social role and physical presentation and appearance to match one's internal gender identity. The formation of each individual's gender identity is complex, multifaceted, and interlaced with the rest of their development. 

## Transgender Identities

The boundary between cisgender, non-cisgender, and transgender is not consistent throughout the literature. Medical literature has a narrower definition of transgender, usually defining it as an individual who was born one gender, and wishes to be the "opposite," e.g. someone who was assigned a man at birth, and wishes to transition to live as a woman [@galupoConstantlyFlowingRiver2017]. However, this rigid definition excludes numerous gender identities that do not fit into strict "man" and "woman" categories. @galupoConstantlyFlowingRiver2017, in a number of interviews with non-binary individuals, find that "transgender" is better understood as any gender identities that are not the gender one was assigned at birth.

This, however, is an incredibly broad definition that doesn't have a lot of diagnostic use. @bradfordSocialPsychologicalHeterogeneity2019 found that, across several psychosocial measures, participant's genders could be grouped into cisgender, binary transgender, and non-binary transgender. This examined aspects of participant's lives such as life satisfaction and social support. They concluded that treating the "transgender community" as a unitary whole may inadequately address unique aspects about non-cisgender groups. 

@dozierBeardsBreastsBodies2005 interviewed a number of transmasculine individuals about their experiences as transgender people and changes in their gender identity over time. While many of her interviewees comfortable identified as transgender men, she also found that there was considerable fluidity across many aspects of identity. Critically, with access to medical interventions such as hormone replacement therapy, sex becomes a mutable aspect of gender expression, and labels such as "transgender man" began to lose their descriptive value and personal significance as an identity. Labels such as "transgender" and "transmasculine" frequently carry typified connotations that do not neatly map onto an individual's identities and gendered experiences.

Furthermore, @tateIntegratingStudyTransgender2014 examine the state of gender research and find large inconsistencies in how gender identity is presumed to form in cisgender people versus transgender people. They find that gender identity is frequently presumed to be a binary, static, and unquestioned aspect of cisgender people, whereas it is treated as an active process of self-categorization in transgender people. They advocate for the integration of cisgender and transgender gender research into one cohesive body of work that avoids assuming any in/activity or binary pattern in the formation of anyone's identity. 

Guided by insights from @dozierBeardsBreastsBodies2005 and @tateIntegratingStudyTransgender2014, the author had many discussions about gender identity and transgender identity with her peers, adviser, and friends. She found that there are some people who do not identify as cisgender, but also do not identify as transgender. Furthermore, in the author's own transition, she has moved from identifying as non-binary, to a woman, to retaining some aspects of womanhood, but deriving more of her gender identity from her sexual orientation as a butch lesbian. Thus, she believes that "transgender identity" does not serve much use beyond a broad umbrella term, and is better understood as each individual's identification or lack of identification with many different labels. 

## Gendered Pronouns

Gendered pronouns are commonly recognized in trans literature as an important aspect of trans people's lives, but is rarely elaborated on further (e.g. @diamondTransgenderExperienceIdentity2011). The literature has recognized that use of one's chosen name and pronouns is critical to supporting and affirming trans people. However, little attention has been paid to the details of trans people's relationships with their pronouns. 

Misgendering—the use of a pronoun that refers to someone in a way that is incongruent with their gender—is a common and, sadly, almost everyday experience for some trans people. @mclemoreExperiencesMisgenderingIdentity2015 examined the frequency to which non-cisgender people are misgendered, and the impact that has on a number of psychosocial measures. For example, they found that misgendering causes trans people to feel stigmatized and makes them feel worse. Misgendering was shown to have significant negative impacts on mental health and self-confidence in trans people. 

However, this still leaves the question of why trans people choose the pronouns they do and how they relate to their pronouns. @mcglashanUseAnyPronouns2018 performed a year-long ethnography of transgender schoolchildren in New Zealand who were part of an after school "Rainbow Group." They found that relationships to pronouns are complicated and fluid. Some students were frustrated that their options were limited and could not capture their gender identity. Others also took issue with the static nature of pronouns—in order to capture fluctuations in relationship to their gender, they prefer to change pronouns every meeting. Additionally, the instructors were concerned that requiring students to share their pronouns would be limiting and box them in. 

This was, sadly, the *only* piece of literature the author found that was explicitly about individual's relationships to pronouns. Thus, much of the study was guided by her own experience as a transgender person.

## Transgender Congruence Scale

@kozeeMeasuringTransgenderIndividuals2012 developed the Transgender Congruence Scale (TCS) to quantify how congruent transgender people feel between their internal gender identity. The TCS was developed and validated on a transgender population. The TCS was included to provide a previously validated measure of congruence to evaluate how closely pronouns are related to one's relationship and closeness with their gender identity. 

## Transgender Inclusive Behavior Scale

@kattariDevelopmentValidationTransgender2018 developed the Transgender Inclusive Behavior Scale (TIBS) to quantify how many trans-inclusive behaviors people do. It includes questions about a number of behaviors, including sharing and asking for pronouns, using gender-neutral language, and keeping oneself up-to-date on policies that may affect trans people's lives. The TIBS was developed and validated for people of all genders, trans and cis. We included the TIBS as a proxy measure for how supportive one is of trans people by how conscientiously they practice trans-inclusive behaviors. 
