# Discussion

## Gender Identity

Gender identity is frequently assumed to be a binary or trinary, i.e. men, women, and—perhaps—non-binary people. In the present study, we created seven artificial gender groups based on answers to a series of questions that disaggregated gender identity (e.g. woman, agender, non-binary) and mode of relating to gender identity (e.g. cis, trans, non-binary). These groups are artificial in the sense that they do not fully convey any one participant's gender and were formed from participants' responses to questions about whether they identified as cisgender, transgender, and non-binary, and whether they wrote that they were a man or woman in the write-in gender field. 

In the present study, "non-binary" could be someone's gender, or it could be part of how they relate to their gender. There were 14 participants who indicated that they were non-binary, but did not describe their gender identity with the phrase "non-binary." This includes trans men and women, agender people, genderfluid people, and people who describe their gender as, simply, "queer." Within some circles of the trans community, it is understood that "non-binary" is an umbrella term that includes many different genders. However, in the author's experience, outside of the trans community, "non-binary" is commonly misunderstood as a discrete third gender. The data here indicate that this is a significant mistake, as there are numerous robust differences between the cis non-binary, non-binary, and trans non-binary groups. Even within these groups, the present methodology fails to capture many important aspects of gendered experiences. 

For example, the present study intentionally did not ask participants what their sex or gender assigned at birth was. The author believes that this information is generally not as useful as many make it out to be, especially for research focused on social experiences of gender. However, this means that we were not able to make many inferences about, for example, transmisogyny, beyond comparing trans women to the other groups. Present queer discourse recognizes that, while for the purposes of third-parties, trans women and cis women are the same, trans women face unique issues such as transmisogyny—the specific fear and prejudice against trans women. Transmisogyny is a combination of misogyny and transphobia. Other transfeminine people face transmisogyny because they are perceived as trans women, but do not identify as women. Thus, transmisogyny affected/exempt have become possible categories that gendered experiences can fall in to [@hollebAZGenderSexuality2019]. 

Future gender research should expand the lens of gendered experiences and gender identities beyond three genders, but should be careful to not seek out new binaries. At a minimum, gender should be collected in a write-in field, as this does not privilege certain gender identities over others. Even using the themes from a previous study as a definitive list of gender identities should be avoided. For example, no one in the present sample identified as Two-Spirit, an indigenous identity that can have tribe-specific meanings [@ristockAboriginalTwoSpiritLGBTQ2012] and—importantly—does not fit into Western gender systems. A series of checkboxes using data from the present study would fail to include Two-Spirit people. 

Future gender research should also consider the implications that words such as "transgender," "genderqueer," and "non-binary" may carry. For example, while performing the analysis for the present study, the author shared some of her work. She received a number of questions about the "cis non-binary" category. After explaining that placement into the cis non-binary category was based off of how participants responded to questions about being cisgender and non-binary, people generally understood the role the category played. However, this made it clear to the author that "non-binary" is frequently considered a non-cisgender gender identity, and not as a possible way of relating to one's gender that they were assigned at birth. 

Even "non-cisgender" is not a clear category. In order to compare our sample to [@mclemoreExperiencesMisgenderingIdentity2015], we compared their data to participants who indicated that they were not cisgender. However, this was only possible because we did not have any gender-related inclusion criteria and asked participants if they were cisgender. There were multiple differences between the cis non-binary group and the rest of the participants. So, this begs the question, would the participants who fell into the cis non-binary group have responded if we had only sought out non-cisgender participants? Presently, the author does not think she has the right data to answer this question. Future gender-related studies should be careful about possible implications that their inclusion/exclusion criteria carry and be sensitive to local variation.

This also has broader implications for how gender identity is discussed. For example, one common phrase is "trans and non-binary people" (e.g. @thetrevorprojectGuideBeingAlly2020). This could potentially be interpreted as treating transgender people and non-binary people as two seperate groups. However, as we can see from the number of trans non-binary people in the sample, as well as from the diverse array of identities participants reported, the phrase does not perfectly match up to the reality of many gender identities. The author thinks that what's meant by the phrase is "transgender and/or non-binary people" or "non-cisgender people," but this too has its flaws. "Non-cisgender people" then focuses the language on the existence of cis people, potentially making it counterproductive against generally showing an inclusive, trans-competent message. "Transgender and/or non-binary people" may come off as clunky language to people accustomed to the original phrase. The author believes that language used to communicate gender identity should not remain fixed and should strive to balance accuracy, clarity, and inclusiveness. 

## Pronouns

To the authors knowledge, this is the first quantitative study that has been done with an explicit focus on pronouns. The data show that undergraduates at Reed College use a every possible combination of gendered English pronouns, i.e. every combination of "he," "she," and "they." 

There was broad variation of pronoun usage within genders. By allowing participants to note their pronouns separately from their gender, we were able to get a more complete view of how pronoun usage varies across genders. While men and women *mostly* used he/him and she/her pronouns respectively, there were many departures from this, including many cisgender people who exclusively use they/them pronouns, and one woman who uses he/him pronouns. Additionally, we saw non-binary people using all possible combinations of pronouns, including exclusively they/them, she/her, and he/him. While there were many unsurprising trends between gender identity and pronoun usage, there were no hard and fast rules. 

Knowing an individual's gender identity or pronouns does not reveal what the other is. Especially given the limitation of three main pronouns in English, it is a fallacy to presume that everyone will be able to choose pronouns that perfectly represent their gender identity. This is supported by responses to item 14 (“I feel that my internal gender identity and pronouns are consistent with one another.”). If everyone was able to choose pronouns that perfectly represented their gender identity, we should not see significant variation between genders. However, we found significant differences between genders *and* pronouns, demonstrating the inadequacy of pronouns at representing gender identity. 

There was also variation in the order of the pronouns. For example, some participants who use they/them and she/her pronouns wrote "they/she," and others wrote "she/they." The order of pronouns was not analyzed in the present study. However, as the author has used many pronouns in her life, she knows that order may reflect any number of reasons, including preference or contextual usage. Some participants wrote elaborately about their complicated relationship with pronouns in the write-in field. This is to say that, for many people, relationships with pronouns extends beyond a simple statement of "they/them" or "he/him," and may vary with closeness, context, or feelings. 

## Experiences with Misgendering

@mclemoreExperiencesMisgenderingIdentity2015 examined differences in misgendering frequency and felt stigma when misgendered in a non-cisgender population. We extended their study by administering their items to cis participants as well. We found robust differences between cis people and non-cis people in both misgendering frequency and felt stigma. This shows that trans and non-binary people have a significantly worse experience with pronouns—they get misgendered more frequently and feel more stigmatized when misgendered. 

We also extended @mclemoreExperiencesMisgenderingIdentity2015 by including between-gender and between-pronoun comparisons. Interestingly, non-binary people reported feeling less stigmatized when misgendered than trans men and trans non-binary people. We found that gender congruence, as measured by the TCS, had significant effects on misgendering frequency as well as felt stigma. The author speculates that individuals who intentionally identify as transgender may care more about being gendered correctly. However, further study is needed to examine the feelings misgendering invokes. 

It should also be noted that people who use only they/them pronouns reported being misgendered more than everyone else. Significant work needs to be done to normalize they/them pronouns, independent of gender presentation and appearance. 

## Gender Congruence

@kozeeMeasuringTransgenderIndividuals2012 developed the TCS to provide a measure of gender congruence for transgender people. However, we administered the TCS to cisgender people as well. We found that cis men and women experience significantly higher gender congruence than trans and non-binary people. While this isn't surprising, it's impressive that the results are so clear-cut.

## Transgender Inclusive Behaviors

@kattariDevelopmentValidationTransgender2018 developed the TIBS to provide a measure of how many trans-inclusive behaviors people do. The TIBS was developed for people of all genders. We found that cis men set a low bar—they perform significantly fewer trans-inclusive behaviors than every other gender group. Interestingly, cis women perform significantly more trans-inclusive behaviors than cis men. This may be due to social forces such as misogyny forcing cis women to be more aware of issues that affect trans people, or the absence of misogyny and transphobia allowing cis men to ignore issues that affect trans people. 

## Primary Component Analysis

Use of PCA allowed us to reduce responses to all of the pronoun-related questions to three main components. As previously discussed, the first component loadings indicated that it captured consistency between others’ perception of one’s gender, others’ assumptions about gender and pronouns, misgendering, and comfort when with people with similar genders. This can be interpreted to represent how strongly one is affected by cisnormativity.

Examining the variation between gender groups within the first component yields some interesting results. Firstly, as previously discussed, the distribution of individuals is likely bimodal. We can interpret this as experiences with cisnormativity falling into two groups. One could reasonably label these as cisgender and transgender. Even non-binary individuals who did not say that they were transgender fall much further to the transgender side, however we can see from the Tukey test that they are not as affected as the trans non-binary group. These data concretely show that non-cisgender people broadly have a very different experience navigating the world as their gender. This doesn't just manifest as different access to spaces, but as a different awareness around how their body and gender presentation is being perceived and evaluated by other people. Cis people may be entirely unaware of certain common assumptions people make about their gender and body, whereas trans and non-binary people may be acutely aware of them. 

Interestingly, trans men and cis non-binary people show the greatest variation along the first component. Cisness and manhood are both systematically privileged identities that, regardless of if the individual consents to it or not, *may* benefit them. Some trans men and cis non-binary people may benefit from these identities and be less affected by cisnormativiy. However,it should be noted that these two groups exhibit the greatest *variation*—indicating that any given member could have a very trans or very cis experience with cisnormativity. 

Loadings from the second component indicated that it captured one’s desire to share one’s pronouns in various settings and well as how comfortable one feels doing so. Thus, the second component can be interpreted as one's readiness to share their pronouns. 

Examine the variation between gender groups within the second component indicates that readiness to share one's pronouns may not be mediated by one single variable. It may be that cis men are uncomfortable making their gender explicit because they are frequently privileged enough to not have to think about it regularly, and so may not be as ready to share their pronouns. Trans women, on the other hand, experience lower gender congruence, and so may be more concerned that, if they say their pronouns, they will draw unwanted attention to themselves. This is reflected in the data on trans women in the third component. 

The author strongly cautions against making any connection between cis men and trans women's lower readiness to share their pronouns and their gender assigned at birth—as the data show, trans women and cis men have *very* different experiences in *many* ways. Attempting to draw out such a conclusion is contrived at best and transphobic at worst. Furthermore, the difference between non-binary people and transgender women indicate that there is something unique about non-cisgender experiences that make trans women less ready to share their pronouns. 

Loadings from the third component indicated that it captured concern that sharing one’s pronouns will draw unwanted attention, as well as when others—not necessarily of the same gender—share their pronouns first and how consistent and representative one’s pronouns are with one’s gender. Thus, the third component can be interpreted as concern around sharing pronouns and fears of judgment or lack of understanding about one’s pronouns.

Analysis of the variance in the third component indicates that non-binary people are least concerned that sharing their pronouns will draw unwanted attention. It may be that, with the large population of non-binary students at Reed, they are less concerned that sharing their pronouns will make them stand out from everyone else. Or, it could be that non-binary people, as a product of the cisnormative society that we all live in where pronouns are often assumed from appearance, are used to sharing and correcting other people on their pronouns. After having done it countless times, non-binary people may be (sadly) habituated to misgendering and thus exhibit less concern because they expect to have to share their pronouns. 

When the third component is visualized, it appears that trans men and women are slightly more concerned that sharing their pronouns will draw unwanted attention than the rest of the gender groups. This may be because trans men and women have cisnormative-ascribed standards of "passing," or standards of appearance where a naive person may assume that they are cisgender. Passing is a fraught concept that is mired in Eurocentric beauty standards and a transphobic hierarchy of appearances. Yet, for trans men and women—as the author can attest—it is virtually unavoidable. Because sharing one's pronouns may make a trans person's gender more apparent and, perhaps, in contrast to their physical appearance, trans men and women may be more concerned that sharing their pronouns will draw unwanted attention because they are concerned that they may not "pass" to others. It should be noted that this is entirely the fault of a cisnormative society and cis people that exerts pressure on trans people to conform to certain typified appearances that may be unattainable or not desired by the trans person. 

It should also be noted that, cis men, cis women, and trans non-binary people exhibit the least variation along the third component. This may be because these groups are most likely to use a single pronoun, and so their experiences, while likely all different from each other, are consistent when gender is controlled for (by the first component).

<!-- ## Transmisogyny/Trans-Woman Specific Issues -->

## Limitations

Due to the global pandemic that occurred in early 2020, available time for data collection and analysis was limited. However, there are several shortcomings in this study. Firstly, most of the analysis was limited to gender and pronoun effects. While important, gender identity does not exist alone. Gender identity exists in crossroads with countless other identities. @millerThisReallyInteresting2019 provide an account of how queerness and disability intersect in university students. Taking their framework and extending the analysis of this data to examine intersectional effects of age, ethnicity, and major should be done to obtain a clearer picture of how Reedies experience navigating the institution as their gender. 

Furthermore, to expedite analysis, gender groups were created. While this yielded some interesting and novel results, closer analysis could be done by using the many gender-related variables. For example, while we were able to compare cis and trans men, use of the gender groups prevented us from examining if manhood itself exerted any effects. While this would complicate the analysis required, we have the privilege of a large amount of very high-resolution data gender-related data. It would be a shame to not fully utilize it. 

Additionally, it must be acknowledged that the scope of this study is limited to undergraduates from Reed College. This is a *very specific population* and likely does not generalize well. While this study may prove useful in guiding other research on pronouns and gives us a unique opportunity to make institution-specific recommendations, these items should be re-assessed and administered to a more diverse population in age, ethnicity, socio-economic class, and education, to name a few. 
